name: CI

on:
  pull_request:
    types: closed
    branches: master

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // マージされていない場合は何もしない
            if (!context.payload.pull_request.merged){
              return
            }

            // PR作成（web）
            const pr_title_web = `prod web #${context.payload.number}`
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: pr_title_web,
              head: 'master',
              base: 'deploy_web',
              body: pr_title_web,
            }).then(result => {
              console.log('PR(web) : 作成完了')
            }).catch(e => {
              console.log('下記のエラーが発生したため、PR(web)作成を中止しました。')
              console.log(e.message)
            })

            // PR作成（client）
            const pr_title_client = `prod client #${context.payload.number}`
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: pr_title_client,
              head: 'master',
              base: 'deploy_client',
              body: pr_title_client,
            }).then(result => {
              console.log('PR(client) : 作成完了')
            }).catch(e => {
              console.log('下記のエラーが発生したため、PR(client)作成を中止しました。')
              console.log(e.message)
            })
