name: CI

on:
  pull_request:
    types: closed
    branches: master

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // マージされていない場合は何もしない
            if (!context.payload.pull_request.merged) {
                return
            }

            // PR作成（web）
            const pr_title_web = `prod web #${context.payload.number}`
            github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: pr_title_web,
                head: 'master',
                base: 'deploy_web',
                body: pr_title_web,
            }).then(result => {
                console.log('PR(web) : 作成完了')
            }).catch(e => {
                e.errors.map(t => {
                    if (t.message !== undefined && t.message.includes("A pull request already exists")) {
                        // 同等のPRが存在している場合は、元PRにコメントする
                        createPRComment()
                    } else {
                        console.log('下記のエラーが発生したため、PR(おちるやつ)作成を中止しました。')
                        console.log(e.message)
                    }
                })
            })

            // PR作成（client）
            const pr_title_client = `prod client #${context.payload.number}`
            github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: pr_title_client,
                head: 'master',
                base: 'deploy_client',
                body: pr_title_client,
            }).then(result => {
                console.log('PR(client) : 作成完了')
            }).catch(e => {
                e.errors.map(t => {
                    if (t.message !== undefined && t.message.includes("A pull request already exists")) {
                        // 同等のPRが存在している場合は、元PRにコメントする
                        createPRComment()
                    } else {
                        console.log('下記のエラーが発生したため、PR(おちるやつ)作成を中止しました。')
                        console.log(e.message)
                    }
                })
            })

            // これは絶対落ちるやつ（ブランチが存在しない）
            const pr_title_err = `これはおちます`
            github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: pr_title_err,
                head: 'blank',
                base: 'deploy_client',
                body: pr_title_err,
            }).then(result => {
                console.log('PR(おちるやつ) : 作成完了')
            }).catch(e => {
                e.errors.map(t => {
                    if (t.message !== undefined && t.message.includes("A pull request already exists")) {
                        // 同等のPRが存在している場合は、元PRにコメントする
                        createPRComment()
                    } else {
                        console.log('下記のエラーが発生したため、PR(おちるやつ)作成を中止しました。')
                        console.log(e.message)
                    }
                })
            })

            const createPRComment = () => {

                console.log("=> 元PRのBASE")
                console.log(context.payload.pull_request.base)
                console.log("=> 元PRのHEAD")
                console.log(context.payload.pull_request.head)


                github.search.issuesAndPullRequests({
                    q: "is:pr is:open "
                }).then(result => {
                    console.log("=> 検索結果")
                    console.log(result)
                })



                // github.issues.createComment({
                //     owner: context.repo.owner,
                //     repo: context.repo.repo,
                //     issue_number: context.payload.number,
                //     body: `同じものが存在していたよ`,
                // })
                // console.log("=> context")
                // console.log(context)
                console.log("同じのが存在してました")
            }
