name: CI

on:
  pull_request:
    types: closed
    branches: master

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('=> context')
            console.log(context)

            console.log('=> タイトル')
            console.log(`prod web ${context.payload.number}`)

            // マージされていない場合は何もしない
            if (!context.payload.pull_request.merged){
              console.log('マージされていないので抜けます')
              return
            }

            console.log('マージされたので作るよ')

            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `prod web #${context.payload.number}`,
              head: 'master',
              base: 'deploy',
              body: `prod web #${context.payload.number}`,
            }).catch(e => {
              console.error('下記のエラーが発生したため、PR作成を中止しました')
              console.error(e.message)
            })
