name: CI

on:
  pull_request:
    types: closed
    branches: master

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // マージされていない場合は何もしない
            if (!context.payload.pull_request.merged) {
                return
            }

            // PR作成
            const createPR = (setting) => {
                github.pulls.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: setting.title,
                    head: setting.head,
                    base: setting.base,
                    body: setting.title,
                }).then(result => {
                    console.log(`PR(${setting.note}) : 作成完了`)
                }).catch(e => {
                    e.errors.map(t => {
                        if (t.message !== undefined && t.message.includes(`A pull request already exists`)) {
                            // 同等のPRが存在している場合は、元PRにコメントする
                            createSamePRComment(setting)
                        } else {
                            console.log(`PR(${setting.note}) : 下記のエラーが発生したため、作成を中止しました。`)
                            console.log(e.message)
                        }
                    })
                })
            }

            // 同等のPRが存在している場合は、元PRにコメントする
            const createSamePRComment = (setting) => {

                github.search.issuesAndPullRequests({
                    q: `is:pr is:open head:${setting.head} base:${setting.base}`
                }).then(result => {

                    let same_pr_number = ``
                    result.data.items.map((t, i) => {
                        same_pr_number = i > 0 ? `#${same_pr_number}, #${t.number}` : `#${t.number}`
                    })

                    const pr_info = `PR(${setting.note}) : 同等のPRがすでに存在しています => ${same_pr_number}`
                    github.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.payload.number,
                        body: pr_info,
                    })

                    console.log(pr_info)
                })
            }

            // 新しく作成するPRの設定
            const settings = {
                web: { title: `prod web #${context.payload.number}`, head: `master`, base: `deploy_web`, note: `web` },
                client: { title: `prod client #${context.payload.number}`, head: `master`, base: `deploy_client`, note: `client` },
                test: { title: `これは落ちます`, head: `master`, base: `naiyo`, note: `落ちるやつ` }
            }

            // PR作成（web）
            createPR(settings.web)

            // PR作成（client）
            createPR(settings.client)

            // これは絶対落ちるやつ（ブランチが存在しない）
            createPR(settings.test)
