name: CI

on: 
  pull_request:
    types: closed
    branches: master

jobs:
  create_pr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
