name: CI_comment

on:
  pull_request:
    types: opened
    branches: master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const headBranchName = context.payload.pull_request.head.ref;

            let ENV_NAME = "";
            let ROOT_DIR_NAME = "";

            const regex = new RegExp("^demo[0-2]/", "g");
            const envNameArray = regex.exec(headBranchName);
            if (envNameArray !== null) {
              ENV_NAME = envNameArray[0];
              ROOT_DIR_NAME = headBranchName.slice(regex.lastIndex);
            }

            console.log(ENV_NAME)
            console.log(ROOT_DIR_NAME)

            const url_info = `URL => https://${ENV_NAME}.hoge.fuga/${ROOT_DIR_NAME}index.html`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: url_info,
            });
